from typing import Any, Dict, List

# 关系类型说明
# PREREQUISITE: 先修于，学习A必须先掌握B
# CONTAINS:     包含，上位概念A包含下位概念B
# IMPLEMENTS:   实现，A是对概念B的具体代码实现案例
# EXTENDS:      扩展，A是B的深化进阶版
# RELATED:      相关，同一语境常一起出现，无强方向依赖

CHAPTERS: List[Dict[str, Any]] = [
    {"chapter_id": "CH01", "title": "引言", "order": 1},
    {"chapter_id": "CH02", "title": "用C语言编写程序", "order": 2},
    {"chapter_id": "CH03", "title": "分支结构", "order": 3},
    {"chapter_id": "CH04", "title": "循环结构", "order": 4},
    {"chapter_id": "CH05", "title": "函数", "order": 5},
    {"chapter_id": "CH06", "title": "数据类型与表达式", "order": 6},
    {"chapter_id": "CH07", "title": "数组", "order": 7},
    {"chapter_id": "CH08", "title": "指针", "order": 8},
    {"chapter_id": "CH09", "title": "结构", "order": 9},
    {"chapter_id": "CH10", "title": "函数与程序结构", "order": 10},
    {"chapter_id": "CH11", "title": "指针进阶", "order": 11},
    {"chapter_id": "CH12", "title": "文件", "order": 12},
]

KNOWLEDGE_POINTS: List[Dict[str, Any]] = [
    {"kp_id": "KP0001", "chapter_id": "CH01", "section": "1.1", "category": "algorithm", "name": "程序设计基本概念", "aliases": "程序,编程", "source": "seed", "reviewed": True},
    {"kp_id": "KP0002", "chapter_id": "CH01", "section": "1.2", "category": "algorithm", "name": "算法与流程图", "aliases": "流程图,伪代码", "source": "seed", "reviewed": True},
    {"kp_id": "KP0003", "chapter_id": "CH01", "section": "1.3", "category": "syntax", "name": "C语言特点与历史", "aliases": "C语言发展", "source": "seed", "reviewed": True},
    {"kp_id": "KP0004", "chapter_id": "CH01", "section": "1.4", "category": "syntax", "name": "程序开发流程", "aliases": "编译,链接,调试", "source": "seed", "reviewed": True},
    {"kp_id": "KP0005", "chapter_id": "CH01", "section": "1.5", "category": "algorithm", "name": "结构化程序设计", "aliases": "顺序结构,分支结构,循环结构", "source": "seed", "reviewed": True},
    {"kp_id": "KP0101", "chapter_id": "CH02", "section": "2.1", "category": "syntax", "name": "C程序基本结构", "aliases": "main函数,头文件", "source": "seed", "reviewed": True},
    {"kp_id": "KP0102", "chapter_id": "CH02", "section": "2.2", "category": "datatype", "name": "变量与常量", "aliases": "变量定义,常量定义", "source": "seed", "reviewed": True},
    {"kp_id": "KP0103", "chapter_id": "CH02", "section": "2.2", "category": "datatype", "name": "整型数据类型", "aliases": "int,short,long", "source": "seed", "reviewed": True},
    {"kp_id": "KP0104", "chapter_id": "CH02", "section": "2.2", "category": "datatype", "name": "浮点型数据类型", "aliases": "float,double", "source": "seed", "reviewed": True},
    {"kp_id": "KP0105", "chapter_id": "CH02", "section": "2.3", "category": "syntax", "name": "算术运算符", "aliases": "加减乘除,取余", "source": "seed", "reviewed": True},
    {"kp_id": "KP0106", "chapter_id": "CH02", "section": "2.3", "category": "syntax", "name": "赋值运算符", "aliases": "赋值表达式,复合赋值", "source": "seed", "reviewed": True},
    {"kp_id": "KP0107", "chapter_id": "CH02", "section": "2.4", "category": "syntax", "name": "格式化输入输出", "aliases": "printf,scanf", "source": "seed", "reviewed": True},
    {"kp_id": "KP0108", "chapter_id": "CH02", "section": "2.5", "category": "syntax", "name": "顺序结构程序设计", "aliases": "顺序执行", "source": "seed", "reviewed": True},
    {"kp_id": "KP0201", "chapter_id": "CH03", "section": "3.1", "category": "control", "name": "if语句", "aliases": "单分支,条件语句", "source": "seed", "reviewed": True},
    {"kp_id": "KP0202", "chapter_id": "CH03", "section": "3.1", "category": "control", "name": "if-else语句", "aliases": "双分支", "source": "seed", "reviewed": True},
    {"kp_id": "KP0203", "chapter_id": "CH03", "section": "3.1", "category": "control", "name": "else-if语句", "aliases": "多分支,嵌套if", "source": "seed", "reviewed": True},
    {"kp_id": "KP0204", "chapter_id": "CH03", "section": "3.2", "category": "datatype", "name": "字符型数据", "aliases": "char,字符常量,字符变量", "source": "seed", "reviewed": True},
    {"kp_id": "KP0205", "chapter_id": "CH03", "section": "3.2", "category": "syntax", "name": "关系运算符", "aliases": "比较运算,关系表达式", "source": "seed", "reviewed": True},
    {"kp_id": "KP0206", "chapter_id": "CH03", "section": "3.2", "category": "syntax", "name": "逻辑运算符", "aliases": "&&,||,!,逻辑表达式", "source": "seed", "reviewed": True},
    {"kp_id": "KP0207", "chapter_id": "CH03", "section": "3.3", "category": "control", "name": "switch语句", "aliases": "多分支选择,case,default", "source": "seed", "reviewed": True},
    {"kp_id": "KP0208", "chapter_id": "CH03", "section": "3.3", "category": "control", "name": "break语句", "aliases": "跳出switch", "source": "seed", "reviewed": True},
    {"kp_id": "KP0301", "chapter_id": "CH04", "section": "4.1", "category": "control", "name": "for语句", "aliases": "for循环,计数循环", "source": "seed", "reviewed": True},
    {"kp_id": "KP0302", "chapter_id": "CH04", "section": "4.2", "category": "control", "name": "while语句", "aliases": "while循环,当型循环", "source": "seed", "reviewed": True},
    {"kp_id": "KP0303", "chapter_id": "CH04", "section": "4.3", "category": "control", "name": "do-while语句", "aliases": "直到型循环", "source": "seed", "reviewed": True},
    {"kp_id": "KP0304", "chapter_id": "CH04", "section": "4.4", "category": "control", "name": "break与continue", "aliases": "跳出循环,跳过当次", "source": "seed", "reviewed": True},
    {"kp_id": "KP0305", "chapter_id": "CH04", "section": "4.5", "category": "control", "name": "嵌套循环", "aliases": "多重循环,二重循环", "source": "seed", "reviewed": True},
    {"kp_id": "KP0306", "chapter_id": "CH04", "section": "4.6", "category": "algorithm", "name": "循环程序设计方法", "aliases": "穷举,迭代,累加累乘", "source": "seed", "reviewed": True},
    {"kp_id": "KP0401", "chapter_id": "CH05", "section": "5.1", "category": "function", "name": "函数定义", "aliases": "函数头,函数体,返回类型", "source": "seed", "reviewed": True},
    {"kp_id": "KP0402", "chapter_id": "CH05", "section": "5.2", "category": "function", "name": "函数调用", "aliases": "实参,形参", "source": "seed", "reviewed": True},
    {"kp_id": "KP0403", "chapter_id": "CH05", "section": "5.2", "category": "function", "name": "参数传递", "aliases": "值传递,传值调用", "source": "seed", "reviewed": True},
    {"kp_id": "KP0404", "chapter_id": "CH05", "section": "5.3", "category": "function", "name": "函数返回值", "aliases": "return语句,返回类型", "source": "seed", "reviewed": True},
    {"kp_id": "KP0405", "chapter_id": "CH05", "section": "5.4", "category": "function", "name": "函数声明", "aliases": "函数原型,前向声明", "source": "seed", "reviewed": True},
    {"kp_id": "KP0406", "chapter_id": "CH05", "section": "5.5", "category": "function", "name": "递归函数", "aliases": "递归调用,递归算法", "source": "seed", "reviewed": True},
    {"kp_id": "KP0407", "chapter_id": "CH05", "section": "5.6", "category": "function", "name": "标准库函数", "aliases": "math.h,string.h,stdlib.h", "source": "seed", "reviewed": True},
    {"kp_id": "KP0501", "chapter_id": "CH06", "section": "6.1", "category": "datatype", "name": "整型类型详解", "aliases": "有符号,无符号,整型范围", "source": "seed", "reviewed": True},
    {"kp_id": "KP0502", "chapter_id": "CH06", "section": "6.1", "category": "datatype", "name": "浮点类型精度", "aliases": "double精度,float误差", "source": "seed", "reviewed": True},
    {"kp_id": "KP0503", "chapter_id": "CH06", "section": "6.2", "category": "datatype", "name": "类型转换", "aliases": "隐式转换,强制转换,cast", "source": "seed", "reviewed": True},
    {"kp_id": "KP0504", "chapter_id": "CH06", "section": "6.3", "category": "syntax", "name": "运算符优先级", "aliases": "优先级,结合性", "source": "seed", "reviewed": True},
    {"kp_id": "KP0505", "chapter_id": "CH06", "section": "6.4", "category": "syntax", "name": "自增自减运算符", "aliases": "++,--,前缀,后缀", "source": "seed", "reviewed": True},
    {"kp_id": "KP0506", "chapter_id": "CH06", "section": "6.5", "category": "syntax", "name": "条件表达式", "aliases": "三目运算符,?:", "source": "seed", "reviewed": True},
    {"kp_id": "KP0507", "chapter_id": "CH06", "section": "6.6", "category": "syntax", "name": "位运算符", "aliases": "&,|,^,~,<<,>>,按位运算", "source": "seed", "reviewed": True},
    {"kp_id": "KP0601", "chapter_id": "CH07", "section": "7.1", "category": "datatype", "name": "一维数组", "aliases": "数组定义,数组下标", "source": "seed", "reviewed": True},
    {"kp_id": "KP0602", "chapter_id": "CH07", "section": "7.2", "category": "datatype", "name": "二维数组", "aliases": "矩阵,多维数组", "source": "seed", "reviewed": True},
    {"kp_id": "KP0603", "chapter_id": "CH07", "section": "7.3", "category": "datatype", "name": "字符数组", "aliases": "char数组,字符串数组", "source": "seed", "reviewed": True},
    {"kp_id": "KP0604", "chapter_id": "CH07", "section": "7.3", "category": "datatype", "name": "字符串操作函数", "aliases": "strlen,strcpy,strcmp,strcat", "source": "seed", "reviewed": True},
    {"kp_id": "KP0605", "chapter_id": "CH07", "section": "7.4", "category": "function", "name": "数组作函数参数", "aliases": "数组传参", "source": "seed", "reviewed": True},
    {"kp_id": "KP0606", "chapter_id": "CH07", "section": "7.5", "category": "algorithm", "name": "排序算法", "aliases": "冒泡排序,选择排序,插入排序", "source": "seed", "reviewed": True},
    {"kp_id": "KP0607", "chapter_id": "CH07", "section": "7.5", "category": "algorithm", "name": "查找算法", "aliases": "顺序查找,二分查找", "source": "seed", "reviewed": True},
    {"kp_id": "KP0701", "chapter_id": "CH08", "section": "8.1.2", "category": "memory", "name": "地址与指针概念", "aliases": "内存地址,指针的含义", "source": "seed", "reviewed": True},
    {"kp_id": "KP0702", "chapter_id": "CH08", "section": "8.1.3", "category": "memory", "name": "指针变量的定义", "aliases": "指针定义,指针声明", "source": "seed", "reviewed": True},
    {"kp_id": "KP0703", "chapter_id": "CH08", "section": "8.1.4", "category": "memory", "name": "指针的基本运算", "aliases": "指针加减,*运算符,&运算符", "source": "seed", "reviewed": True},
    {"kp_id": "KP0704", "chapter_id": "CH08", "section": "8.1.5", "category": "memory", "name": "指针变量的初始化", "aliases": "指针初始化,NULL指针", "source": "seed", "reviewed": True},
    {"kp_id": "KP0705", "chapter_id": "CH08", "section": "8.2.2", "category": "memory", "name": "指针作函数参数", "aliases": "传址调用,引用传递", "source": "seed", "reviewed": True},
    {"kp_id": "KP0706", "chapter_id": "CH08", "section": "8.2", "category": "memory", "name": "指针与数组", "aliases": "数组指针,指针下标,指针遍历数组", "source": "seed", "reviewed": True},
    {"kp_id": "KP0707", "chapter_id": "CH08", "section": "8.3", "category": "algorithm", "name": "冒泡排序指针实现", "aliases": "指针排序,冒泡排序", "source": "seed", "reviewed": True},
    {"kp_id": "KP0708", "chapter_id": "CH08", "section": "8.4", "category": "memory", "name": "字符串压缩", "aliases": "指针操作字符串,字符串处理", "source": "seed", "reviewed": True},
    {"kp_id": "KP0709", "chapter_id": "CH08", "section": "8.5", "category": "function", "name": "任意个整数求和", "aliases": "可变参数,指针数组应用", "source": "seed", "reviewed": True},
    {"kp_id": "KP0801", "chapter_id": "CH09", "section": "9.1", "category": "datatype", "name": "结构体定义", "aliases": "struct,结构类型", "source": "seed", "reviewed": True},
    {"kp_id": "KP0802", "chapter_id": "CH09", "section": "9.2", "category": "datatype", "name": "结构体变量", "aliases": "结构变量,结构体初始化", "source": "seed", "reviewed": True},
    {"kp_id": "KP0803", "chapter_id": "CH09", "section": "9.3", "category": "datatype", "name": "结构体数组", "aliases": "结构数组", "source": "seed", "reviewed": True},
    {"kp_id": "KP0804", "chapter_id": "CH09", "section": "9.4", "category": "memory", "name": "结构体指针", "aliases": "指向结构的指针,->运算符", "source": "seed", "reviewed": True},
    {"kp_id": "KP0805", "chapter_id": "CH09", "section": "9.5", "category": "datatype", "name": "共用体", "aliases": "union,联合体", "source": "seed", "reviewed": True},
    {"kp_id": "KP0806", "chapter_id": "CH09", "section": "9.6", "category": "datatype", "name": "枚举类型", "aliases": "enum,枚举常量", "source": "seed", "reviewed": True},
    {"kp_id": "KP0807", "chapter_id": "CH09", "section": "9.7", "category": "syntax", "name": "typedef", "aliases": "类型别名,typedef定义", "source": "seed", "reviewed": True},
    {"kp_id": "KP0901", "chapter_id": "CH10", "section": "10.1", "category": "function", "name": "变量作用域", "aliases": "局部变量,全局变量", "source": "seed", "reviewed": True},
    {"kp_id": "KP0902", "chapter_id": "CH10", "section": "10.2", "category": "function", "name": "存储类别", "aliases": "auto,static,extern,register", "source": "seed", "reviewed": True},
    {"kp_id": "KP0903", "chapter_id": "CH10", "section": "10.3", "category": "function", "name": "内部函数与外部函数", "aliases": "static函数,extern函数", "source": "seed", "reviewed": True},
    {"kp_id": "KP0904", "chapter_id": "CH10", "section": "10.4", "category": "syntax", "name": "预处理指令", "aliases": "#define,#include,宏定义", "source": "seed", "reviewed": True},
    {"kp_id": "KP0905", "chapter_id": "CH10", "section": "10.5", "category": "syntax", "name": "多文件程序结构", "aliases": "头文件,模块化编程", "source": "seed", "reviewed": True},
    {"kp_id": "KP1001", "chapter_id": "CH11", "section": "11.1", "category": "memory", "name": "指向指针的指针", "aliases": "二级指针,**", "source": "seed", "reviewed": True},
    {"kp_id": "KP1002", "chapter_id": "CH11", "section": "11.2", "category": "memory", "name": "动态内存分配", "aliases": "malloc,calloc,free,realloc", "source": "seed", "reviewed": True},
    {"kp_id": "KP1003", "chapter_id": "CH11", "section": "11.3", "category": "function", "name": "函数指针", "aliases": "指向函数的指针,回调函数", "source": "seed", "reviewed": True},
    {"kp_id": "KP1004", "chapter_id": "CH11", "section": "11.4", "category": "memory", "name": "链表", "aliases": "单链表,链表操作,动态链表", "source": "seed", "reviewed": True},
    {"kp_id": "KP1005", "chapter_id": "CH11", "section": "11.5", "category": "memory", "name": "命令行参数", "aliases": "argc,argv,main参数", "source": "seed", "reviewed": True},
    {"kp_id": "KP1101", "chapter_id": "CH12", "section": "12.1", "category": "syntax", "name": "文件概念", "aliases": "文本文件,二进制文件", "source": "seed", "reviewed": True},
    {"kp_id": "KP1102", "chapter_id": "CH12", "section": "12.2", "category": "syntax", "name": "文件打开与关闭", "aliases": "fopen,fclose,FILE指针", "source": "seed", "reviewed": True},
    {"kp_id": "KP1103", "chapter_id": "CH12", "section": "12.3", "category": "syntax", "name": "文件读写操作", "aliases": "fread,fwrite,fgets,fputs", "source": "seed", "reviewed": True},
    {"kp_id": "KP1104", "chapter_id": "CH12", "section": "12.4", "category": "syntax", "name": "格式化文件读写", "aliases": "fprintf,fscanf", "source": "seed", "reviewed": True},
    {"kp_id": "KP1105", "chapter_id": "CH12", "section": "12.5", "category": "syntax", "name": "文件定位", "aliases": "fseek,ftell,rewind", "source": "seed", "reviewed": True},
    {"kp_id": "KP1106", "chapter_id": "CH12", "section": "12.6", "category": "syntax", "name": "错误处理", "aliases": "ferror,feof,perror", "source": "seed", "reviewed": True},
]

RELATIONS: List[Dict[str, Any]] = [
    # CONTAINS
    {"source": "KP0005", "target": "KP0108", "relation_type": "CONTAINS", "description": "结构化程序设计包含顺序结构"},
    {"source": "KP0005", "target": "KP0201", "relation_type": "CONTAINS", "description": "结构化程序设计包含分支结构-if"},
    {"source": "KP0005", "target": "KP0207", "relation_type": "CONTAINS", "description": "结构化程序设计包含分支结构-switch"},
    {"source": "KP0005", "target": "KP0301", "relation_type": "CONTAINS", "description": "结构化程序设计包含循环结构-for"},
    {"source": "KP0005", "target": "KP0302", "relation_type": "CONTAINS", "description": "结构化程序设计包含循环结构-while"},
    {"source": "KP0005", "target": "KP0303", "relation_type": "CONTAINS", "description": "结构化程序设计包含循环结构-do-while"},
    {"source": "KP0102", "target": "KP0103", "relation_type": "CONTAINS", "description": "变量与常量包含整型数据类型"},
    {"source": "KP0102", "target": "KP0104", "relation_type": "CONTAINS", "description": "变量与常量包含浮点型数据类型"},
    {"source": "KP0102", "target": "KP0204", "relation_type": "CONTAINS", "description": "变量与常量包含字符型数据"},
    {"source": "KP0201", "target": "KP0202", "relation_type": "CONTAINS", "description": "if语句包含if-else双分支形式"},
    {"source": "KP0201", "target": "KP0203", "relation_type": "CONTAINS", "description": "if语句包含else-if多分支形式"},
    {"source": "KP0601", "target": "KP0602", "relation_type": "CONTAINS", "description": "一维数组概念扩展包含二维数组"},
    {"source": "KP0601", "target": "KP0603", "relation_type": "CONTAINS", "description": "一维数组包含字符数组这一特殊形式"},
    {"source": "KP0801", "target": "KP0802", "relation_type": "CONTAINS", "description": "结构体定义包含结构体变量的使用"},
    {"source": "KP0801", "target": "KP0803", "relation_type": "CONTAINS", "description": "结构体定义包含结构体数组"},
    {"source": "KP0801", "target": "KP0804", "relation_type": "CONTAINS", "description": "结构体定义包含结构体指针访问方式"},
    {"source": "KP0701", "target": "KP0702", "relation_type": "CONTAINS", "description": "地址与指针概念包含指针变量的定义"},
    {"source": "KP0701", "target": "KP0703", "relation_type": "CONTAINS", "description": "地址与指针概念包含指针的基本运算"},
    {"source": "KP0701", "target": "KP0704", "relation_type": "CONTAINS", "description": "地址与指针概念包含指针变量的初始化"},
    {"source": "KP1102", "target": "KP1103", "relation_type": "CONTAINS", "description": "文件打开关闭包含文件读写操作"},
    {"source": "KP1103", "target": "KP1104", "relation_type": "CONTAINS", "description": "文件读写操作包含格式化文件读写"},
    {"source": "KP1103", "target": "KP1105", "relation_type": "CONTAINS", "description": "文件读写操作包含文件定位"},
    # PREREQUISITE
    {"source": "KP0001", "target": "KP0101", "relation_type": "PREREQUISITE", "description": "程序设计概念是编写C程序的前提"},
    {"source": "KP0004", "target": "KP0101", "relation_type": "PREREQUISITE", "description": "程序开发流程是C程序结构的前提"},
    {"source": "KP0102", "target": "KP0201", "relation_type": "PREREQUISITE", "description": "变量与数据类型是学分支结构的前提"},
    {"source": "KP0205", "target": "KP0201", "relation_type": "PREREQUISITE", "description": "关系运算是if条件判断的前提"},
    {"source": "KP0206", "target": "KP0201", "relation_type": "PREREQUISITE", "description": "逻辑运算是复杂条件判断的前提"},
    {"source": "KP0201", "target": "KP0301", "relation_type": "PREREQUISITE", "description": "分支结构是循环结构的前提"},
    {"source": "KP0301", "target": "KP0401", "relation_type": "PREREQUISITE", "description": "循环结构是函数设计的前提"},
    {"source": "KP0401", "target": "KP0601", "relation_type": "PREREQUISITE", "description": "函数是数组参数传递的前提"},
    {"source": "KP0601", "target": "KP0701", "relation_type": "PREREQUISITE", "description": "一维数组是理解指针与数组关系的前提"},
    {"source": "KP0603", "target": "KP0701", "relation_type": "PREREQUISITE", "description": "字符数组是理解指针与字符串的前提"},
    {"source": "KP0702", "target": "KP0703", "relation_type": "PREREQUISITE", "description": "指针变量定义是指针运算的前提"},
    {"source": "KP0702", "target": "KP0704", "relation_type": "PREREQUISITE", "description": "指针变量定义是指针初始化的前提"},
    {"source": "KP0703", "target": "KP0705", "relation_type": "PREREQUISITE", "description": "指针运算是指针作函数参数的前提"},
    {"source": "KP0704", "target": "KP0706", "relation_type": "PREREQUISITE", "description": "指针初始化是指针与数组操作的前提"},
    {"source": "KP0706", "target": "KP0707", "relation_type": "PREREQUISITE", "description": "指针与数组是冒泡排序指针实现的前提"},
    {"source": "KP0706", "target": "KP0708", "relation_type": "PREREQUISITE", "description": "指针与数组是字符串压缩的前提"},
    {"source": "KP0705", "target": "KP0709", "relation_type": "PREREQUISITE", "description": "指针作函数参数是任意整数求和的前提"},
    {"source": "KP0802", "target": "KP0803", "relation_type": "PREREQUISITE", "description": "结构体变量是结构体数组的前提"},
    {"source": "KP0802", "target": "KP0804", "relation_type": "PREREQUISITE", "description": "结构体变量是结构体指针使用的前提"},
    {"source": "KP0401", "target": "KP0901", "relation_type": "PREREQUISITE", "description": "函数是理解变量作用域的前提"},
    {"source": "KP0901", "target": "KP0902", "relation_type": "PREREQUISITE", "description": "变量作用域是存储类别的前提"},
    {"source": "KP0902", "target": "KP0903", "relation_type": "PREREQUISITE", "description": "存储类别是内外部函数区分的前提"},
    {"source": "KP0904", "target": "KP0905", "relation_type": "PREREQUISITE", "description": "预处理指令是多文件结构的前提"},
    {"source": "KP0702", "target": "KP1001", "relation_type": "PREREQUISITE", "description": "指针变量是二级指针的前提"},
    {"source": "KP0702", "target": "KP1002", "relation_type": "PREREQUISITE", "description": "指针变量是动态内存分配的前提"},
    {"source": "KP0401", "target": "KP1003", "relation_type": "PREREQUISITE", "description": "函数定义是函数指针的前提"},
    {"source": "KP0702", "target": "KP1003", "relation_type": "PREREQUISITE", "description": "指针变量是函数指针的前提"},
    {"source": "KP1002", "target": "KP1004", "relation_type": "PREREQUISITE", "description": "动态内存分配是链表实现的前提"},
    {"source": "KP0804", "target": "KP1004", "relation_type": "PREREQUISITE", "description": "结构体指针是链表节点设计的前提"},
    {"source": "KP1101", "target": "KP1102", "relation_type": "PREREQUISITE", "description": "文件概念是文件打开关闭操作的前提"},
    {"source": "KP1102", "target": "KP1103", "relation_type": "PREREQUISITE", "description": "文件打开是文件读写的前提"},
    {"source": "KP1103", "target": "KP1106", "relation_type": "PREREQUISITE", "description": "文件读写是错误处理的前提"},
    {"source": "KP0701", "target": "KP0801", "relation_type": "PREREQUISITE", "description": "指针是结构体指针访问的前提"},
    {"source": "KP0801", "target": "KP1001", "relation_type": "PREREQUISITE", "description": "结构体是指针进阶综合应用的前提"},
    {"source": "KP0701", "target": "KP1001", "relation_type": "PREREQUISITE", "description": "指针基础是二级指针等进阶概念的前提"},
    {"source": "KP1001", "target": "KP1101", "relation_type": "PREREQUISITE", "description": "指针进阶是文件指针操作的前提"},
    # EXTENDS
    {"source": "KP0501", "target": "KP0103", "relation_type": "EXTENDS", "description": "整型类型详解是整型数据类型的深化"},
    {"source": "KP0502", "target": "KP0104", "relation_type": "EXTENDS", "description": "浮点类型精度是浮点型数据类型的深化"},
    {"source": "KP0503", "target": "KP0105", "relation_type": "EXTENDS", "description": "类型转换是算术运算符类型规则的深化"},
    {"source": "KP0504", "target": "KP0105", "relation_type": "EXTENDS", "description": "运算符优先级是算术运算符的系统化深化"},
    {"source": "KP0505", "target": "KP0105", "relation_type": "EXTENDS", "description": "自增自减是算术运算符的特殊形式深化"},
    {"source": "KP1001", "target": "KP0702", "relation_type": "EXTENDS", "description": "指向指针的指针是指针变量定义的进阶"},
    {"source": "KP1002", "target": "KP0702", "relation_type": "EXTENDS", "description": "动态内存分配是指针变量应用的进阶"},
    {"source": "KP1003", "target": "KP0401", "relation_type": "EXTENDS", "description": "函数指针是函数定义概念的进阶"},
    {"source": "KP1004", "target": "KP0801", "relation_type": "EXTENDS", "description": "链表是结构体指针的综合进阶应用"},
    {"source": "KP0406", "target": "KP0401", "relation_type": "EXTENDS", "description": "递归函数是函数定义的深化形式"},
    {"source": "KP0605", "target": "KP0601", "relation_type": "EXTENDS", "description": "数组作函数参数是一维数组的扩展应用"},
    {"source": "KP0606", "target": "KP0301", "relation_type": "EXTENDS", "description": "排序算法是for循环的典型综合应用"},
    {"source": "KP0707", "target": "KP0606", "relation_type": "EXTENDS", "description": "冒泡排序指针实现是排序算法的指针版深化"},
    # RELATED
    {"source": "KP0105", "target": "KP0106", "relation_type": "RELATED", "description": "算术运算符与赋值运算符密切相关"},
    {"source": "KP0201", "target": "KP0202", "relation_type": "RELATED", "description": "if语句与if-else是分支控制的核心"},
    {"source": "KP0202", "target": "KP0203", "relation_type": "RELATED", "description": "if-else与else-if是分支扩展关系"},
    {"source": "KP0207", "target": "KP0208", "relation_type": "RELATED", "description": "switch语句与break语句配合使用"},
    {"source": "KP0301", "target": "KP0302", "relation_type": "RELATED", "description": "for循环与while循环都是循环结构"},
    {"source": "KP0302", "target": "KP0303", "relation_type": "RELATED", "description": "while与do-while是条件循环的两种形式"},
    {"source": "KP0304", "target": "KP0301", "relation_type": "RELATED", "description": "break与continue常用于for循环"},
    {"source": "KP0304", "target": "KP0302", "relation_type": "RELATED", "description": "break与continue也用于while循环"},
    {"source": "KP0305", "target": "KP0301", "relation_type": "RELATED", "description": "嵌套循环基于for循环实现"},
    {"source": "KP0402", "target": "KP0403", "relation_type": "RELATED", "description": "函数调用与参数传递密切相关"},
    {"source": "KP0401", "target": "KP0405", "relation_type": "RELATED", "description": "函数定义与函数声明互补"},
    {"source": "KP0504", "target": "KP0505", "relation_type": "RELATED", "description": "运算符优先级与自增自减常一起讨论"},
    {"source": "KP0601", "target": "KP0605", "relation_type": "RELATED", "description": "一维数组与数组作函数参数直接关联"},
    {"source": "KP0603", "target": "KP0604", "relation_type": "RELATED", "description": "字符数组与字符串操作函数配套使用"},
    {"source": "KP0606", "target": "KP0607", "relation_type": "RELATED", "description": "排序算法与查找算法是数组算法两大主题"},
    {"source": "KP0703", "target": "KP0706", "relation_type": "RELATED", "description": "指针运算是理解指针与数组的基础"},
    {"source": "KP0705", "target": "KP0706", "relation_type": "RELATED", "description": "指针作函数参数与指针和数组常一起使用"},
    {"source": "KP0805", "target": "KP0806", "relation_type": "RELATED", "description": "共用体与枚举类型都是C语言自定义类型"},
    {"source": "KP0807", "target": "KP0801", "relation_type": "RELATED", "description": "typedef常用于结构体类型的简化"},
    {"source": "KP0901", "target": "KP0902", "relation_type": "RELATED", "description": "变量作用域与存储类别密切相关"},
    {"source": "KP0904", "target": "KP0905", "relation_type": "RELATED", "description": "预处理指令与多文件结构配合使用"},
    {"source": "KP1001", "target": "KP1002", "relation_type": "RELATED", "description": "二级指针与动态内存分配常组合使用"},
    {"source": "KP1103", "target": "KP1104", "relation_type": "RELATED", "description": "文件读写与格式化文件读写直接相关"},
    {"source": "KP1105", "target": "KP1106", "relation_type": "RELATED", "description": "文件定位与错误处理都是文件操作的辅助功能"},
] 